/** @openagentaudit/core/report — skeleton. */
import type { CanonicalEvent, Finding, RiskScore } from '@openagentaudit/schema';

export interface ReportBundle {
  markdown: string;
  html: string;
  json: string;
}

export async function renderReport(
  _events: CanonicalEvent[],
  _findings: Finding[],
  _score: RiskScore,
): Promise<ReportBundle> {
  return {
    markdown: '# Audit report (skeleton)\n\n_Generated by @openagentaudit/core skeleton._',
    html: '<h1>Audit report (skeleton)</h1>',
    json: '{}',
  };
}
